<?php

declare(strict_types=1);

namespace Library\DateTime;

class TimeZone
{
    public const AFRICA_ABIDJAN                 = 'Africa/Abidjan';
    public const AFRICA_ACCRA                   = 'Africa/Accra';
    public const AFRICA_ADDIS_ABABA             = 'Africa/Addis_Ababa';
    public const AFRICA_ALGIERS                 = 'Africa/Algiers';
    public const AFRICA_ASMARA                  = 'Africa/Asmara';
    public const AFRICA_BAMAKO                  = 'Africa/Bamako';
    public const AFRICA_BANGUI                  = 'Africa/Bangui';
    public const AFRICA_BANJUL                  = 'Africa/Banjul';
    public const AFRICA_BISSAU                  = 'Africa/Bissau';
    public const AFRICA_BLANTYRE                = 'Africa/Blantyre';
    public const AFRICA_BRAZZAVILLE             = 'Africa/Brazzaville';
    public const AFRICA_BUJUMBURA               = 'Africa/Bujumbura';
    public const AFRICA_CAIRO                   = 'Africa/Cairo';
    public const AFRICA_CASABLANCA              = 'Africa/Casablanca';
    public const AFRICA_CEUTA                   = 'Africa/Ceuta';
    public const AFRICA_CONAKRY                 = 'Africa/Conakry';
    public const AFRICA_DAKAR                   = 'Africa/Dakar';
    public const AFRICA_DAR_ES_SALAAM           = 'Africa/Dar_es_Salaam';
    public const AFRICA_DJIBOUTI                = 'Africa/Djibouti';
    public const AFRICA_DOUALA                  = 'Africa/Douala';
    public const AFRICA_EL_AAIUN                = 'Africa/El_Aaiun';
    public const AFRICA_FREETOWN                = 'Africa/Freetown';
    public const AFRICA_GABORONE                = 'Africa/Gaborone';
    public const AFRICA_HARARE                  = 'Africa/Harare';
    public const AFRICA_JOHANNESBURG            = 'Africa/Johannesburg';
    public const AFRICA_JUBA                    = 'Africa/Juba';
    public const AFRICA_KAMPALA                 = 'Africa/Kampala';
    public const AFRICA_KHARTOUM                = 'Africa/Khartoum';
    public const AFRICA_KIGALI                  = 'Africa/Kigali';
    public const AFRICA_KINSHASA                = 'Africa/Kinshasa';
    public const AFRICA_LAGOS                   = 'Africa/Lagos';
    public const AFRICA_LIBREVILLE              = 'Africa/Libreville';
    public const AFRICA_LOME                    = 'Africa/Lome';
    public const AFRICA_LUANDA                  = 'Africa/Luanda';
    public const AFRICA_LUBUMBASHI              = 'Africa/Lubumbashi';
    public const AFRICA_LUSAKA                  = 'Africa/Lusaka';
    public const AFRICA_MALABO                  = 'Africa/Malabo';
    public const AFRICA_MAPUTO                  = 'Africa/Maputo';
    public const AFRICA_MASERU                  = 'Africa/Maseru';
    public const AFRICA_MBABANE                 = 'Africa/Mbabane';
    public const AFRICA_MOGADISHU               = 'Africa/Mogadishu';
    public const AFRICA_MONROVIA                = 'Africa/Monrovia';
    public const AFRICA_NAIROBI                 = 'Africa/Nairobi';
    public const AFRICA_NDJAMENA                = 'Africa/Ndjamena';
    public const AFRICA_NIAMEY                  = 'Africa/Niamey';
    public const AFRICA_NOUAKCHOTT              = 'Africa/Nouakchott';
    public const AFRICA_OUAGADOUGOU             = 'Africa/Ouagadougou';
    public const AFRICA_PORTO_NOVO              = 'Africa/Porto-Novo';
    public const AFRICA_SAO_TOME                = 'Africa/Sao_Tome';
    public const AFRICA_TRIPOLI                 = 'Africa/Tripoli';
    public const AFRICA_TUNIS                   = 'Africa/Tunis';
    public const AFRICA_WINDHOEK                = 'Africa/Windhoek';
    public const AMERICA_ADAK                   = 'America/Adak';
    public const AMERICA_ANCHORAGE              = 'America/Anchorage';
    public const AMERICA_ANGUILLA               = 'America/Anguilla';
    public const AMERICA_ANTIGUA                = 'America/Antigua';
    public const AMERICA_ARAGUAINA              = 'America/Araguaina';
    public const AMERICA_ARGENTINA_BUENOS_AIRES = 'America/Argentina/Buenos_Aires';
    public const AMERICA_ARGENTINA_CATAMARCA    = 'America/Argentina/Catamarca';
    public const AMERICA_ARGENTINA_CORDOBA      = 'America/Argentina/Cordoba';
    public const AMERICA_ARGENTINA_JUJUY        = 'America/Argentina/Jujuy';
    public const AMERICA_ARGENTINA_LA_RIOJA     = 'America/Argentina/La_Rioja';
    public const AMERICA_ARGENTINA_MENDOZA      = 'America/Argentina/Mendoza';
    public const AMERICA_ARGENTINA_RIO_GALLEGOS = 'America/Argentina/Rio_Gallegos';
    public const AMERICA_ARGENTINA_SALTA        = 'America/Argentina/Salta';
    public const AMERICA_ARGENTINA_SAN_JUAN     = 'America/Argentina/San_Juan';
    public const AMERICA_ARGENTINA_SAN_LUIS     = 'America/Argentina/San_Luis';
    public const AMERICA_ARGENTINA_TUCUMAN      = 'America/Argentina/Tucuman';
    public const AMERICA_ARGENTINA_USHUAIA      = 'America/Argentina/Ushuaia';
    public const AMERICA_ARUBA                  = 'America/Aruba';
    public const AMERICA_ASUNCION               = 'America/Asuncion';
    public const AMERICA_ATIKOKAN               = 'America/Atikokan';
    public const AMERICA_BAHIA                  = 'America/Bahia';
    public const AMERICA_BAHIA_BANDERAS         = 'America/Bahia_Banderas';
    public const AMERICA_BARBADOS               = 'America/Barbados';
    public const AMERICA_BELEM                  = 'America/Belem';
    public const AMERICA_BELIZE                 = 'America/Belize';
    public const AMERICA_BLANC_SABLON           = 'America/Blanc-Sablon';
    public const AMERICA_BOA_VISTA              = 'America/Boa_Vista';
    public const AMERICA_BOGOTA                 = 'America/Bogota';
    public const AMERICA_BOISE                  = 'America/Boise';
    public const AMERICA_CAMBRIDGE_BAY          = 'America/Cambridge_Bay';
    public const AMERICA_CAMPO_GRANDE           = 'America/Campo_Grande';
    public const AMERICA_CANCUN                 = 'America/Cancun';
    public const AMERICA_CARACAS                = 'America/Caracas';
    public const AMERICA_CAYENNE                = 'America/Cayenne';
    public const AMERICA_CAYMAN                 = 'America/Cayman';
    public const AMERICA_CHICAGO                = 'America/Chicago';
    public const AMERICA_CHIHUAHUA              = 'America/Chihuahua';
    public const AMERICA_COSTA_RICA             = 'America/Costa_Rica';
    public const AMERICA_CRESTON                = 'America/Creston';
    public const AMERICA_CUIABA                 = 'America/Cuiaba';
    public const AMERICA_CURACAO                = 'America/Curacao';
    public const AMERICA_DANMARKSHAVN           = 'America/Danmarkshavn';
    public const AMERICA_DAWSON                 = 'America/Dawson';
    public const AMERICA_DAWSON_CREEK           = 'America/Dawson_Creek';
    public const AMERICA_DENVER                 = 'America/Denver';
    public const AMERICA_DETROIT                = 'America/Detroit';
    public const AMERICA_DOMINICA               = 'America/Dominica';
    public const AMERICA_EDMONTON               = 'America/Edmonton';
    public const AMERICA_EIRUNEPE               = 'America/Eirunepe';
    public const AMERICA_EL_SALVADOR            = 'America/El_Salvador';
    public const AMERICA_FORT_NELSON            = 'America/Fort_Nelson';
    public const AMERICA_FORTALEZA              = 'America/Fortaleza';
    public const AMERICA_GLACE_BAY              = 'America/Glace_Bay';
    public const AMERICA_GOOSE_BAY              = 'America/Goose_Bay';
    public const AMERICA_GRAND_TURK             = 'America/Grand_Turk';
    public const AMERICA_GRENADA                = 'America/Grenada';
    public const AMERICA_GUADELOUPE             = 'America/Guadeloupe';
    public const AMERICA_GUATEMALA              = 'America/Guatemala';
    public const AMERICA_GUAYAQUIL              = 'America/Guayaquil';
    public const AMERICA_GUYANA                 = 'America/Guyana';
    public const AMERICA_HALIFAX                = 'America/Halifax';
    public const AMERICA_HAVANA                 = 'America/Havana';
    public const AMERICA_HERMOSILLO             = 'America/Hermosillo';
    public const AMERICA_INDIANA_INDIANAPOLIS   = 'America/Indiana/Indianapolis';
    public const AMERICA_INDIANA_KNOX           = 'America/Indiana/Knox';
    public const AMERICA_INDIANA_MARENGO        = 'America/Indiana/Marengo';
    public const AMERICA_INDIANA_PETERSBURG     = 'America/Indiana/Petersburg';
    public const AMERICA_INDIANA_TELL_CITY      = 'America/Indiana/Tell_City';
    public const AMERICA_INDIANA_VEVAY          = 'America/Indiana/Vevay';
    public const AMERICA_INDIANA_VINCENNES      = 'America/Indiana/Vincennes';
    public const AMERICA_INDIANA_WINAMAC        = 'America/Indiana/Winamac';
    public const AMERICA_INUVIK                 = 'America/Inuvik';
    public const AMERICA_IQALUIT                = 'America/Iqaluit';
    public const AMERICA_JAMAICA                = 'America/Jamaica';
    public const AMERICA_JUNEAU                 = 'America/Juneau';
    public const AMERICA_KENTUCKY_LOUISVILLE    = 'America/Kentucky/Louisville';
    public const AMERICA_KENTUCKY_MONTICELLO    = 'America/Kentucky/Monticello';
    public const AMERICA_KRALENDIJK             = 'America/Kralendijk';
    public const AMERICA_LA_PAZ                 = 'America/La_Paz';
    public const AMERICA_LIMA                   = 'America/Lima';
    public const AMERICA_LOS_ANGELES            = 'America/Los_Angeles';
    public const AMERICA_LOWER_PRINCES          = 'America/Lower_Princes';
    public const AMERICA_MACEIO                 = 'America/Maceio';
    public const AMERICA_MANAGUA                = 'America/Managua';
    public const AMERICA_MANAUS                 = 'America/Manaus';
    public const AMERICA_MARIGOT                = 'America/Marigot';
    public const AMERICA_MARTINIQUE             = 'America/Martinique';
    public const AMERICA_MATAMOROS              = 'America/Matamoros';
    public const AMERICA_MAZATLAN               = 'America/Mazatlan';
    public const AMERICA_MENOMINEE              = 'America/Menominee';
    public const AMERICA_MERIDA                 = 'America/Merida';
    public const AMERICA_METLAKATLA             = 'America/Metlakatla';
    public const AMERICA_MEXICO_CITY            = 'America/Mexico_City';
    public const AMERICA_MIQUELON               = 'America/Miquelon';
    public const AMERICA_MONCTON                = 'America/Moncton';
    public const AMERICA_MONTERREY              = 'America/Monterrey';
    public const AMERICA_MONTEVIDEO             = 'America/Montevideo';
    public const AMERICA_MONTSERRAT             = 'America/Montserrat';
    public const AMERICA_NASSAU                 = 'America/Nassau';
    public const AMERICA_NEW_YORK               = 'America/New_York';
    public const AMERICA_NIPIGON                = 'America/Nipigon';
    public const AMERICA_NOME                   = 'America/Nome';
    public const AMERICA_NORONHA                = 'America/Noronha';
    public const AMERICA_NORTH_DAKOTA_BEULAH    = 'America/North_Dakota/Beulah';
    public const AMERICA_NORTH_DAKOTA_CENTER    = 'America/North_Dakota/Center';
    public const AMERICA_NORTH_DAKOTA_NEW_SALEM = 'America/North_Dakota/New_Salem';
    public const AMERICA_NUUK                   = 'America/Nuuk';
    public const AMERICA_OJINAGA                = 'America/Ojinaga';
    public const AMERICA_PANAMA                 = 'America/Panama';
    public const AMERICA_PANGNIRTUNG            = 'America/Pangnirtung';
    public const AMERICA_PARAMARIBO             = 'America/Paramaribo';
    public const AMERICA_PHOENIX                = 'America/Phoenix';
    public const AMERICA_PORT_AU_PRINCE         = 'America/Port-au-Prince';
    public const AMERICA_PORT_OF_SPAIN          = 'America/Port_of_Spain';
    public const AMERICA_PORTO_VELHO            = 'America/Porto_Velho';
    public const AMERICA_PUERTO_RICO            = 'America/Puerto_Rico';
    public const AMERICA_PUNTA_ARENAS           = 'America/Punta_Arenas';
    public const AMERICA_RAINY_RIVER            = 'America/Rainy_River';
    public const AMERICA_RANKIN_INLET           = 'America/Rankin_Inlet';
    public const AMERICA_RECIFE                 = 'America/Recife';
    public const AMERICA_REGINA                 = 'America/Regina';
    public const AMERICA_RESOLUTE               = 'America/Resolute';
    public const AMERICA_RIO_BRANCO             = 'America/Rio_Branco';
    public const AMERICA_SANTAREM               = 'America/Santarem';
    public const AMERICA_SANTIAGO               = 'America/Santiago';
    public const AMERICA_SANTO_DOMINGO          = 'America/Santo_Domingo';
    public const AMERICA_SAO_PAULO              = 'America/Sao_Paulo';
    public const AMERICA_SCORESBYSUND           = 'America/Scoresbysund';
    public const AMERICA_SITKA                  = 'America/Sitka';
    public const AMERICA_ST_BARTHELEMY          = 'America/St_Barthelemy';
    public const AMERICA_ST_JOHNS               = 'America/St_Johns';
    public const AMERICA_ST_KITTS               = 'America/St_Kitts';
    public const AMERICA_ST_LUCIA               = 'America/St_Lucia';
    public const AMERICA_ST_THOMAS              = 'America/St_Thomas';
    public const AMERICA_ST_VINCENT             = 'America/St_Vincent';
    public const AMERICA_SWIFT_CURRENT          = 'America/Swift_Current';
    public const AMERICA_TEGUCIGALPA            = 'America/Tegucigalpa';
    public const AMERICA_THULE                  = 'America/Thule';
    public const AMERICA_THUNDER_BAY            = 'America/Thunder_Bay';
    public const AMERICA_TIJUANA                = 'America/Tijuana';
    public const AMERICA_TORONTO                = 'America/Toronto';
    public const AMERICA_TORTOLA                = 'America/Tortola';
    public const AMERICA_VANCOUVER              = 'America/Vancouver';
    public const AMERICA_WHITEHORSE             = 'America/Whitehorse';
    public const AMERICA_WINNIPEG               = 'America/Winnipeg';
    public const AMERICA_YAKUTAT                = 'America/Yakutat';
    public const AMERICA_YELLOWKNIFE            = 'America/Yellowknife';
    public const ANTARCTICA_CASEY               = 'Antarctica/Casey';
    public const ANTARCTICA_DAVIS               = 'Antarctica/Davis';
    public const ANTARCTICA_DUMONTDURVILLE      = 'Antarctica/DumontDUrville';
    public const ANTARCTICA_MACQUARIE           = 'Antarctica/Macquarie';
    public const ANTARCTICA_MAWSON              = 'Antarctica/Mawson';
    public const ANTARCTICA_MCMURDO             = 'Antarctica/McMurdo';
    public const ANTARCTICA_PALMER              = 'Antarctica/Palmer';
    public const ANTARCTICA_ROTHERA             = 'Antarctica/Rothera';
    public const ANTARCTICA_SYOWA               = 'Antarctica/Syowa';
    public const ANTARCTICA_TROLL               = 'Antarctica/Troll';
    public const ANTARCTICA_VOSTOK              = 'Antarctica/Vostok';
    public const ARCTIC_LONGYEARBYEN            = 'Arctic/Longyearbyen';
    public const ASIA_ADEN                      = 'Asia/Aden';
    public const ASIA_ALMATY                    = 'Asia/Almaty';
    public const ASIA_AMMAN                     = 'Asia/Amman';
    public const ASIA_ANADYR                    = 'Asia/Anadyr';
    public const ASIA_AQTAU                     = 'Asia/Aqtau';
    public const ASIA_AQTOBE                    = 'Asia/Aqtobe';
    public const ASIA_ASHGABAT                  = 'Asia/Ashgabat';
    public const ASIA_ATYRAU                    = 'Asia/Atyrau';
    public const ASIA_BAGHDAD                   = 'Asia/Baghdad';
    public const ASIA_BAHRAIN                   = 'Asia/Bahrain';
    public const ASIA_BAKU                      = 'Asia/Baku';
    public const ASIA_BANGKOK                   = 'Asia/Bangkok';
    public const ASIA_BARNAUL                   = 'Asia/Barnaul';
    public const ASIA_BEIRUT                    = 'Asia/Beirut';
    public const ASIA_BISHKEK                   = 'Asia/Bishkek';
    public const ASIA_BRUNEI                    = 'Asia/Brunei';
    public const ASIA_CHITA                     = 'Asia/Chita';
    public const ASIA_CHOIBALSAN                = 'Asia/Choibalsan';
    public const ASIA_COLOMBO                   = 'Asia/Colombo';
    public const ASIA_DAMASCUS                  = 'Asia/Damascus';
    public const ASIA_DHAKA                     = 'Asia/Dhaka';
    public const ASIA_DILI                      = 'Asia/Dili';
    public const ASIA_DUBAI                     = 'Asia/Dubai';
    public const ASIA_DUSHANBE                  = 'Asia/Dushanbe';
    public const ASIA_FAMAGUSTA                 = 'Asia/Famagusta';
    public const ASIA_GAZA                      = 'Asia/Gaza';
    public const ASIA_HEBRON                    = 'Asia/Hebron';
    public const ASIA_HO_CHI_MINH               = 'Asia/Ho_Chi_Minh';
    public const ASIA_HONG_KONG                 = 'Asia/Hong_Kong';
    public const ASIA_HOVD                      = 'Asia/Hovd';
    public const ASIA_IRKUTSK                   = 'Asia/Irkutsk';
    public const ASIA_JAKARTA                   = 'Asia/Jakarta';
    public const ASIA_JAYAPURA                  = 'Asia/Jayapura';
    public const ASIA_JERUSALEM                 = 'Asia/Jerusalem';
    public const ASIA_KABUL                     = 'Asia/Kabul';
    public const ASIA_KAMCHATKA                 = 'Asia/Kamchatka';
    public const ASIA_KARACHI                   = 'Asia/Karachi';
    public const ASIA_KATHMANDU                 = 'Asia/Kathmandu';
    public const ASIA_KHANDYGA                  = 'Asia/Khandyga';
    public const ASIA_KOLKATA                   = 'Asia/Kolkata';
    public const ASIA_KRASNOYARSK               = 'Asia/Krasnoyarsk';
    public const ASIA_KUALA_LUMPUR              = 'Asia/Kuala_Lumpur';
    public const ASIA_KUCHING                   = 'Asia/Kuching';
    public const ASIA_KUWAIT                    = 'Asia/Kuwait';
    public const ASIA_MACAU                     = 'Asia/Macau';
    public const ASIA_MAGADAN                   = 'Asia/Magadan';
    public const ASIA_MAKASSAR                  = 'Asia/Makassar';
    public const ASIA_MANILA                    = 'Asia/Manila';
    public const ASIA_MUSCAT                    = 'Asia/Muscat';
    public const ASIA_NICOSIA                   = 'Asia/Nicosia';
    public const ASIA_NOVOKUZNETSK              = 'Asia/Novokuznetsk';
    public const ASIA_NOVOSIBIRSK               = 'Asia/Novosibirsk';
    public const ASIA_OMSK                      = 'Asia/Omsk';
    public const ASIA_ORAL                      = 'Asia/Oral';
    public const ASIA_PHNOM_PENH                = 'Asia/Phnom_Penh';
    public const ASIA_PONTIANAK                 = 'Asia/Pontianak';
    public const ASIA_PYONGYANG                 = 'Asia/Pyongyang';
    public const ASIA_QATAR                     = 'Asia/Qatar';
    public const ASIA_QOSTANAY                  = 'Asia/Qostanay';
    public const ASIA_QYZYLORDA                 = 'Asia/Qyzylorda';
    public const ASIA_RIYADH                    = 'Asia/Riyadh';
    public const ASIA_SAKHALIN                  = 'Asia/Sakhalin';
    public const ASIA_SAMARKAND                 = 'Asia/Samarkand';
    public const ASIA_SEOUL                     = 'Asia/Seoul';
    public const ASIA_SHANGHAI                  = 'Asia/Shanghai';
    public const ASIA_SINGAPORE                 = 'Asia/Singapore';
    public const ASIA_SREDNEKOLYMSK             = 'Asia/Srednekolymsk';
    public const ASIA_TAIPEI                    = 'Asia/Taipei';
    public const ASIA_TASHKENT                  = 'Asia/Tashkent';
    public const ASIA_TBILISI                   = 'Asia/Tbilisi';
    public const ASIA_TEHRAN                    = 'Asia/Tehran';
    public const ASIA_THIMPHU                   = 'Asia/Thimphu';
    public const ASIA_TOKYO                     = 'Asia/Tokyo';
    public const ASIA_TOMSK                     = 'Asia/Tomsk';
    public const ASIA_ULAANBAATAR               = 'Asia/Ulaanbaatar';
    public const ASIA_URUMQI                    = 'Asia/Urumqi';
    public const ASIA_UST_NERA                  = 'Asia/Ust-Nera';
    public const ASIA_VIENTIANE                 = 'Asia/Vientiane';
    public const ASIA_VLADIVOSTOK               = 'Asia/Vladivostok';
    public const ASIA_YAKUTSK                   = 'Asia/Yakutsk';
    public const ASIA_YANGON                    = 'Asia/Yangon';
    public const ASIA_YEKATERINBURG             = 'Asia/Yekaterinburg';
    public const ASIA_YEREVAN                   = 'Asia/Yerevan';
    public const ATLANTIC_AZORES                = 'Atlantic/Azores';
    public const ATLANTIC_BERMUDA               = 'Atlantic/Bermuda';
    public const ATLANTIC_CANARY                = 'Atlantic/Canary';
    public const ATLANTIC_CAPE_VERDE            = 'Atlantic/Cape_Verde';
    public const ATLANTIC_FAROE                 = 'Atlantic/Faroe';
    public const ATLANTIC_MADEIRA               = 'Atlantic/Madeira';
    public const ATLANTIC_REYKJAVIK             = 'Atlantic/Reykjavik';
    public const ATLANTIC_SOUTH_GEORGIA         = 'Atlantic/South_Georgia';
    public const ATLANTIC_ST_HELENA             = 'Atlantic/St_Helena';
    public const ATLANTIC_STANLEY               = 'Atlantic/Stanley';
    public const AUSTRALIA_ADELAIDE             = 'Australia/Adelaide';
    public const AUSTRALIA_BRISBANE             = 'Australia/Brisbane';
    public const AUSTRALIA_BROKEN_HILL          = 'Australia/Broken_Hill';
    public const AUSTRALIA_CURRIE               = 'Australia/Currie';
    public const AUSTRALIA_DARWIN               = 'Australia/Darwin';
    public const AUSTRALIA_EUCLA                = 'Australia/Eucla';
    public const AUSTRALIA_HOBART               = 'Australia/Hobart';
    public const AUSTRALIA_LINDEMAN             = 'Australia/Lindeman';
    public const AUSTRALIA_LORD_HOWE            = 'Australia/Lord_Howe';
    public const AUSTRALIA_MELBOURNE            = 'Australia/Melbourne';
    public const AUSTRALIA_PERTH                = 'Australia/Perth';
    public const AUSTRALIA_SYDNEY               = 'Australia/Sydney';
    public const EUROPE_AMSTERDAM               = 'Europe/Amsterdam';
    public const EUROPE_ANDORRA                 = 'Europe/Andorra';
    public const EUROPE_ASTRAKHAN               = 'Europe/Astrakhan';
    public const EUROPE_ATHENS                  = 'Europe/Athens';
    public const EUROPE_BELGRADE                = 'Europe/Belgrade';
    public const EUROPE_BERLIN                  = 'Europe/Berlin';
    public const EUROPE_BRATISLAVA              = 'Europe/Bratislava';
    public const EUROPE_BRUSSELS                = 'Europe/Brussels';
    public const EUROPE_BUCHAREST               = 'Europe/Bucharest';
    public const EUROPE_BUDAPEST                = 'Europe/Budapest';
    public const EUROPE_BUSINGEN                = 'Europe/Busingen';
    public const EUROPE_CHISINAU                = 'Europe/Chisinau';
    public const EUROPE_COPENHAGEN              = 'Europe/Copenhagen';
    public const EUROPE_DUBLIN                  = 'Europe/Dublin';
    public const EUROPE_GIBRALTAR               = 'Europe/Gibraltar';
    public const EUROPE_GUERNSEY                = 'Europe/Guernsey';
    public const EUROPE_HELSINKI                = 'Europe/Helsinki';
    public const EUROPE_ISLE_OF_MAN             = 'Europe/Isle_of_Man';
    public const EUROPE_ISTANBUL                = 'Europe/Istanbul';
    public const EUROPE_JERSEY                  = 'Europe/Jersey';
    public const EUROPE_KALININGRAD             = 'Europe/Kaliningrad';
    public const EUROPE_KIEV                    = 'Europe/Kiev';
    public const EUROPE_KIROV                   = 'Europe/Kirov';
    public const EUROPE_LISBON                  = 'Europe/Lisbon';
    public const EUROPE_LJUBLJANA               = 'Europe/Ljubljana';
    public const EUROPE_LONDON                  = 'Europe/London';
    public const EUROPE_LUXEMBOURG              = 'Europe/Luxembourg';
    public const EUROPE_MADRID                  = 'Europe/Madrid';
    public const EUROPE_MALTA                   = 'Europe/Malta';
    public const EUROPE_MARIEHAMN               = 'Europe/Mariehamn';
    public const EUROPE_MINSK                   = 'Europe/Minsk';
    public const EUROPE_MONACO                  = 'Europe/Monaco';
    public const EUROPE_MOSCOW                  = 'Europe/Moscow';
    public const EUROPE_OSLO                    = 'Europe/Oslo';
    public const EUROPE_PARIS                   = 'Europe/Paris';
    public const EUROPE_PODGORICA               = 'Europe/Podgorica';
    public const EUROPE_PRAGUE                  = 'Europe/Prague';
    public const EUROPE_RIGA                    = 'Europe/Riga';
    public const EUROPE_ROME                    = 'Europe/Rome';
    public const EUROPE_SAMARA                  = 'Europe/Samara';
    public const EUROPE_SAN_MARINO              = 'Europe/San_Marino';
    public const EUROPE_SARAJEVO                = 'Europe/Sarajevo';
    public const EUROPE_SARATOV                 = 'Europe/Saratov';
    public const EUROPE_SIMFEROPOL              = 'Europe/Simferopol';
    public const EUROPE_SKOPJE                  = 'Europe/Skopje';
    public const EUROPE_SOFIA                   = 'Europe/Sofia';
    public const EUROPE_STOCKHOLM               = 'Europe/Stockholm';
    public const EUROPE_TALLINN                 = 'Europe/Tallinn';
    public const EUROPE_TIRANE                  = 'Europe/Tirane';
    public const EUROPE_ULYANOVSK               = 'Europe/Ulyanovsk';
    public const EUROPE_UZHGOROD                = 'Europe/Uzhgorod';
    public const EUROPE_VADUZ                   = 'Europe/Vaduz';
    public const EUROPE_VATICAN                 = 'Europe/Vatican';
    public const EUROPE_VIENNA                  = 'Europe/Vienna';
    public const EUROPE_VILNIUS                 = 'Europe/Vilnius';
    public const EUROPE_VOLGOGRAD               = 'Europe/Volgograd';
    public const EUROPE_WARSAW                  = 'Europe/Warsaw';
    public const EUROPE_ZAGREB                  = 'Europe/Zagreb';
    public const EUROPE_ZAPOROZHYE              = 'Europe/Zaporozhye';
    public const EUROPE_ZURICH                  = 'Europe/Zurich';
    public const INDIAN_ANTANANARIVO            = 'Indian/Antananarivo';
    public const INDIAN_CHAGOS                  = 'Indian/Chagos';
    public const INDIAN_CHRISTMAS               = 'Indian/Christmas';
    public const INDIAN_COCOS                   = 'Indian/Cocos';
    public const INDIAN_COMORO                  = 'Indian/Comoro';
    public const INDIAN_KERGUELEN               = 'Indian/Kerguelen';
    public const INDIAN_MAHE                    = 'Indian/Mahe';
    public const INDIAN_MALDIVES                = 'Indian/Maldives';
    public const INDIAN_MAURITIUS               = 'Indian/Mauritius';
    public const INDIAN_MAYOTTE                 = 'Indian/Mayotte';
    public const INDIAN_REUNION                 = 'Indian/Reunion';
    public const PACIFIC_APIA                   = 'Pacific/Apia';
    public const PACIFIC_AUCKLAND               = 'Pacific/Auckland';
    public const PACIFIC_BOUGAINVILLE           = 'Pacific/Bougainville';
    public const PACIFIC_CHATHAM                = 'Pacific/Chatham';
    public const PACIFIC_CHUUK                  = 'Pacific/Chuuk';
    public const PACIFIC_EASTER                 = 'Pacific/Easter';
    public const PACIFIC_EFATE                  = 'Pacific/Efate';
    public const PACIFIC_ENDERBURY              = 'Pacific/Enderbury';
    public const PACIFIC_FAKAOFO                = 'Pacific/Fakaofo';
    public const PACIFIC_FIJI                   = 'Pacific/Fiji';
    public const PACIFIC_FUNAFUTI               = 'Pacific/Funafuti';
    public const PACIFIC_GALAPAGOS              = 'Pacific/Galapagos';
    public const PACIFIC_GAMBIER                = 'Pacific/Gambier';
    public const PACIFIC_GUADALCANAL            = 'Pacific/Guadalcanal';
    public const PACIFIC_GUAM                   = 'Pacific/Guam';
    public const PACIFIC_HONOLULU               = 'Pacific/Honolulu';
    public const PACIFIC_KIRITIMATI             = 'Pacific/Kiritimati';
    public const PACIFIC_KOSRAE                 = 'Pacific/Kosrae';
    public const PACIFIC_KWAJALEIN              = 'Pacific/Kwajalein';
    public const PACIFIC_MAJURO                 = 'Pacific/Majuro';
    public const PACIFIC_MARQUESAS              = 'Pacific/Marquesas';
    public const PACIFIC_MIDWAY                 = 'Pacific/Midway';
    public const PACIFIC_NAURU                  = 'Pacific/Nauru';
    public const PACIFIC_NIUE                   = 'Pacific/Niue';
    public const PACIFIC_NORFOLK                = 'Pacific/Norfolk';
    public const PACIFIC_NOUMEA                 = 'Pacific/Noumea';
    public const PACIFIC_PAGO_PAGO              = 'Pacific/Pago_Pago';
    public const PACIFIC_PALAU                  = 'Pacific/Palau';
    public const PACIFIC_PITCAIRN               = 'Pacific/Pitcairn';
    public const PACIFIC_POHNPEI                = 'Pacific/Pohnpei';
    public const PACIFIC_PORT_MORESBY           = 'Pacific/Port_Moresby';
    public const PACIFIC_RAROTONGA              = 'Pacific/Rarotonga';
    public const PACIFIC_SAIPAN                 = 'Pacific/Saipan';
    public const PACIFIC_TAHITI                 = 'Pacific/Tahiti';
    public const PACIFIC_TARAWA                 = 'Pacific/Tarawa';
    public const PACIFIC_TONGATAPU              = 'Pacific/Tongatapu';
    public const PACIFIC_WAKE                   = 'Pacific/Wake';
    public const PACIFIC_WALLIS                 = 'Pacific/Wallis';
    public const UTC                            = 'UTC';

    ////////////////////////////////////////////////////////////////

    public static function getList(): array
    {
        return [
            'Africa/Abidjan'                 => '+00:00',
            'Africa/Accra'                   => '+00:00',
            'Africa/Addis_Ababa'             => '+03:00',
            'Africa/Algiers'                 => '+01:00',
            'Africa/Asmara'                  => '+03:00',
            'Africa/Bamako'                  => '+00:00',
            'Africa/Bangui'                  => '+01:00',
            'Africa/Banjul'                  => '+00:00',
            'Africa/Bissau'                  => '+00:00',
            'Africa/Blantyre'                => '+02:00',
            'Africa/Brazzaville'             => '+01:00',
            'Africa/Bujumbura'               => '+02:00',
            'Africa/Cairo'                   => '+02:00',
            'Africa/Casablanca'              => '+01:00',
            'Africa/Ceuta'                   => '+01:00',
            'Africa/Conakry'                 => '+00:00',
            'Africa/Dakar'                   => '+00:00',
            'Africa/Dar_es_Salaam'           => '+03:00',
            'Africa/Djibouti'                => '+03:00',
            'Africa/Douala'                  => '+01:00',
            'Africa/El_Aaiun'                => '+01:00',
            'Africa/Freetown'                => '+00:00',
            'Africa/Gaborone'                => '+02:00',
            'Africa/Harare'                  => '+02:00',
            'Africa/Johannesburg'            => '+02:00',
            'Africa/Juba'                    => '+03:00',
            'Africa/Kampala'                 => '+03:00',
            'Africa/Khartoum'                => '+02:00',
            'Africa/Kigali'                  => '+02:00',
            'Africa/Kinshasa'                => '+01:00',
            'Africa/Lagos'                   => '+01:00',
            'Africa/Libreville'              => '+01:00',
            'Africa/Lome'                    => '+00:00',
            'Africa/Luanda'                  => '+01:00',
            'Africa/Lubumbashi'              => '+02:00',
            'Africa/Lusaka'                  => '+02:00',
            'Africa/Malabo'                  => '+01:00',
            'Africa/Maputo'                  => '+02:00',
            'Africa/Maseru'                  => '+02:00',
            'Africa/Mbabane'                 => '+02:00',
            'Africa/Mogadishu'               => '+03:00',
            'Africa/Monrovia'                => '+00:00',
            'Africa/Nairobi'                 => '+03:00',
            'Africa/Ndjamena'                => '+01:00',
            'Africa/Niamey'                  => '+01:00',
            'Africa/Nouakchott'              => '+00:00',
            'Africa/Ouagadougou'             => '+00:00',
            'Africa/Porto-Novo'              => '+01:00',
            'Africa/Sao_Tome'                => '+00:00',
            'Africa/Tripoli'                 => '+02:00',
            'Africa/Tunis'                   => '+01:00',
            'Africa/Windhoek'                => '+02:00',
            'America/Adak'                   => '−10:00',
            'America/Anchorage'              => '−09:00',
            'America/Anguilla'               => '−04:00',
            'America/Antigua'                => '−04:00',
            'America/Araguaina'              => '−03:00',
            'America/Argentina/Buenos_Aires' => '−03:00',
            'America/Argentina/Catamarca'    => '−03:00',
            'America/Argentina/Cordoba'      => '−03:00',
            'America/Argentina/Jujuy'        => '−03:00',
            'America/Argentina/La_Rioja'     => '−03:00',
            'America/Argentina/Mendoza'      => '−03:00',
            'America/Argentina/Rio_Gallegos' => '−03:00',
            'America/Argentina/Salta'        => '−03:00',
            'America/Argentina/San_Juan'     => '−03:00',
            'America/Argentina/San_Luis'     => '−03:00',
            'America/Argentina/Tucuman'      => '−03:00',
            'America/Argentina/Ushuaia'      => '−03:00',
            'America/Aruba'                  => '−04:00',
            'America/Asuncion'               => '−04:00',
            'America/Atikokan'               => '−05:00',
            'America/Bahia'                  => '−03:00',
            'America/Bahia_Banderas'         => '−06:00',
            'America/Barbados'               => '−04:00',
            'America/Belem'                  => '−03:00',
            'America/Belize'                 => '−06:00',
            'America/Blanc-Sablon'           => '−04:00',
            'America/Boa_Vista'              => '−04:00',
            'America/Bogota'                 => '−05:00',
            'America/Boise'                  => '−07:00',
            'America/Cambridge_Bay'          => '−07:00',
            'America/Campo_Grande'           => '−04:00',
            'America/Cancun'                 => '−05:00',
            'America/Caracas'                => '−04:00',
            'America/Cayenne'                => '−03:00',
            'America/Cayman'                 => '−05:00',
            'America/Chicago'                => '−06:00',
            'America/Chihuahua'              => '−07:00',
            'America/Costa_Rica'             => '−06:00',
            'America/Creston'                => '−07:00',
            'America/Cuiaba'                 => '−04:00',
            'America/Curacao'                => '−04:00',
            'America/Danmarkshavn'           => '+00:00',
            'America/Dawson'                 => '−07:00',
            'America/Dawson_Creek'           => '−07:00',
            'America/Denver'                 => '−07:00',
            'America/Detroit'                => '−05:00',
            'America/Dominica'               => '−04:00',
            'America/Edmonton'               => '−07:00',
            'America/Eirunepe'               => '−05:00',
            'America/El_Salvador'            => '−06:00',
            'America/Fort_Nelson'            => '−07:00',
            'America/Fortaleza'              => '−03:00',
            'America/Glace_Bay'              => '−04:00',
            'America/Goose_Bay'              => '−04:00',
            'America/Grand_Turk'             => '−05:00',
            'America/Grenada'                => '−04:00',
            'America/Guadeloupe'             => '−04:00',
            'America/Guatemala'              => '−06:00',
            'America/Guayaquil'              => '−05:00',
            'America/Guyana'                 => '−04:00',
            'America/Halifax'                => '−04:00',
            'America/Havana'                 => '−05:00',
            'America/Hermosillo'             => '−07:00',
            'America/Indiana/Indianapolis'   => '−05:00',
            'America/Indiana/Knox'           => '−06:00',
            'America/Indiana/Marengo'        => '−05:00',
            'America/Indiana/Petersburg'     => '−05:00',
            'America/Indiana/Tell_City'      => '−06:00',
            'America/Indiana/Vevay'          => '−05:00',
            'America/Indiana/Vincennes'      => '−05:00',
            'America/Indiana/Winamac'        => '−05:00',
            'America/Inuvik'                 => '−07:00',
            'America/Iqaluit'                => '−05:00',
            'America/Jamaica'                => '−05:00',
            'America/Juneau'                 => '−09:00',
            'America/Kentucky/Louisville'    => '−05:00',
            'America/Kentucky/Monticello'    => '−05:00',
            'America/Kralendijk'             => '−04:00',
            'America/La_Paz'                 => '−04:00',
            'America/Lima'                   => '−05:00',
            'America/Los_Angeles'            => '−08:00',
            'America/Lower_Princes'          => '−04:00',
            'America/Maceio'                 => '−03:00',
            'America/Managua'                => '−06:00',
            'America/Manaus'                 => '−04:00',
            'America/Marigot'                => '−04:00',
            'America/Martinique'             => '−04:00',
            'America/Matamoros'              => '−06:00',
            'America/Mazatlan'               => '−07:00',
            'America/Menominee'              => '−06:00',
            'America/Merida'                 => '−06:00',
            'America/Metlakatla'             => '−09:00',
            'America/Mexico_City'            => '−06:00',
            'America/Miquelon'               => '−03:00',
            'America/Moncton'                => '−04:00',
            'America/Monterrey'              => '−06:00',
            'America/Montevideo'             => '−03:00',
            'America/Montserrat'             => '−04:00',
            'America/Nassau'                 => '−05:00',
            'America/New_York'               => '−05:00',
            'America/Nipigon'                => '−05:00',
            'America/Nome'                   => '−09:00',
            'America/Noronha'                => '−02:00',
            'America/North_Dakota/Beulah'    => '−06:00',
            'America/North_Dakota/Center'    => '−06:00',
            'America/North_Dakota/New_Salem' => '−06:00',
            'America/Nuuk'                   => '−03:00',
            'America/Ojinaga'                => '−07:00',
            'America/Panama'                 => '−05:00',
            'America/Pangnirtung'            => '−05:00',
            'America/Paramaribo'             => '−03:00',
            'America/Phoenix'                => '−07:00',
            'America/Port-au-Prince'         => '−05:00',
            'America/Port_of_Spain'          => '−04:00',
            'America/Porto_Velho'            => '−04:00',
            'America/Puerto_Rico'            => '−04:00',
            'America/Punta_Arenas'           => '−03:00',
            'America/Rainy_River'            => '−06:00',
            'America/Rankin_Inlet'           => '−06:00',
            'America/Recife'                 => '−03:00',
            'America/Regina'                 => '−06:00',
            'America/Resolute'               => '−06:00',
            'America/Rio_Branco'             => '−05:00',
            'America/Santarem'               => '−03:00',
            'America/Santiago'               => '−04:00',
            'America/Santo_Domingo'          => '−04:00',
            'America/Sao_Paulo'              => '−03:00',
            'America/Scoresbysund'           => '−01:00',
            'America/Sitka'                  => '−09:00',
            'America/St_Barthelemy'          => '−04:00',
            'America/St_Johns'               => '−03:30',
            'America/St_Kitts'               => '−04:00',
            'America/St_Lucia'               => '−04:00',
            'America/St_Thomas'              => '−04:00',
            'America/St_Vincent'             => '−04:00',
            'America/Swift_Current'          => '−06:00',
            'America/Tegucigalpa'            => '−06:00',
            'America/Thule'                  => '−04:00',
            'America/Thunder_Bay'            => '−05:00',
            'America/Tijuana'                => '−08:00',
            'America/Toronto'                => '−05:00',
            'America/Tortola'                => '−04:00',
            'America/Vancouver'              => '−08:00',
            'America/Whitehorse'             => '−07:00',
            'America/Winnipeg'               => '−06:00',
            'America/Yakutat'                => '−09:00',
            'America/Yellowknife'            => '−07:00',
            'Antarctica/Casey'               => '+11:00',
            'Antarctica/Davis'               => '+07:00',
            'Antarctica/DumontDUrville'      => '+10:00',
            'Antarctica/Macquarie'           => '+10:00',
            'Antarctica/Mawson'              => '+05:00',
            'Antarctica/McMurdo'             => '+12:00',
            'Antarctica/Palmer'              => '−03:00',
            'Antarctica/Rothera'             => '−03:00',
            'Antarctica/Syowa'               => '+03:00',
            'Antarctica/Troll'               => '+00:00',
            'Antarctica/Vostok'              => '+06:00',
            'Arctic/Longyearbyen'            => '+01:00',
            'Asia/Aden'                      => '+03:00',
            'Asia/Almaty'                    => '+06:00',
            'Asia/Amman'                     => '+02:00',
            'Asia/Anadyr'                    => '+12:00',
            'Asia/Aqtau'                     => '+05:00',
            'Asia/Aqtobe'                    => '+05:00',
            'Asia/Ashgabat'                  => '+05:00',
            'Asia/Atyrau'                    => '+05:00',
            'Asia/Baghdad'                   => '+03:00',
            'Asia/Bahrain'                   => '+03:00',
            'Asia/Baku'                      => '+04:00',
            'Asia/Bangkok'                   => '+07:00',
            'Asia/Barnaul'                   => '+07:00',
            'Asia/Beirut'                    => '+02:00',
            'Asia/Bishkek'                   => '+06:00',
            'Asia/Brunei'                    => '+08:00',
            'Asia/Chita'                     => '+09:00',
            'Asia/Choibalsan'                => '+08:00',
            'Asia/Colombo'                   => '+05:30',
            'Asia/Damascus'                  => '+02:00',
            'Asia/Dhaka'                     => '+06:00',
            'Asia/Dili'                      => '+09:00',
            'Asia/Dubai'                     => '+04:00',
            'Asia/Dushanbe'                  => '+05:00',
            'Asia/Famagusta'                 => '+02:00',
            'Asia/Gaza'                      => '+02:00',
            'Asia/Hebron'                    => '+02:00',
            'Asia/Ho_Chi_Minh'               => '+07:00',
            'Asia/Hong_Kong'                 => '+08:00',
            'Asia/Hovd'                      => '+07:00',
            'Asia/Irkutsk'                   => '+08:00',
            'Asia/Jakarta'                   => '+07:00',
            'Asia/Jayapura'                  => '+09:00',
            'Asia/Jerusalem'                 => '+02:00',
            'Asia/Kabul'                     => '+04:30',
            'Asia/Kamchatka'                 => '+12:00',
            'Asia/Karachi'                   => '+05:00',
            'Asia/Kathmandu'                 => '+05:45',
            'Asia/Khandyga'                  => '+09:00',
            'Asia/Kolkata'                   => '+05:30',
            'Asia/Krasnoyarsk'               => '+07:00',
            'Asia/Kuala_Lumpur'              => '+08:00',
            'Asia/Kuching'                   => '+08:00',
            'Asia/Kuwait'                    => '+03:00',
            'Asia/Macau'                     => '+08:00',
            'Asia/Magadan'                   => '+11:00',
            'Asia/Makassar'                  => '+08:00',
            'Asia/Manila'                    => '+08:00',
            'Asia/Muscat'                    => '+04:00',
            'Asia/Nicosia'                   => '+02:00',
            'Asia/Novokuznetsk'              => '+07:00',
            'Asia/Novosibirsk'               => '+07:00',
            'Asia/Omsk'                      => '+06:00',
            'Asia/Oral'                      => '+05:00',
            'Asia/Phnom_Penh'                => '+07:00',
            'Asia/Pontianak'                 => '+07:00',
            'Asia/Pyongyang'                 => '+09:00',
            'Asia/Qatar'                     => '+03:00',
            'Asia/Qostanay'                  => '+06:00',
            'Asia/Qyzylorda'                 => '+05:00',
            'Asia/Riyadh'                    => '+03:00',
            'Asia/Sakhalin'                  => '+11:00',
            'Asia/Samarkand'                 => '+05:00',
            'Asia/Seoul'                     => '+09:00',
            'Asia/Shanghai'                  => '+08:00',
            'Asia/Singapore'                 => '+08:00',
            'Asia/Srednekolymsk'             => '+11:00',
            'Asia/Taipei'                    => '+08:00',
            'Asia/Tashkent'                  => '+05:00',
            'Asia/Tbilisi'                   => '+04:00',
            'Asia/Tehran'                    => '+03:30',
            'Asia/Thimphu'                   => '+06:00',
            'Asia/Tokyo'                     => '+09:00',
            'Asia/Tomsk'                     => '+07:00',
            'Asia/Ulaanbaatar'               => '+08:00',
            'Asia/Urumqi'                    => '+06:00',
            'Asia/Ust-Nera'                  => '+10:00',
            'Asia/Vientiane'                 => '+07:00',
            'Asia/Vladivostok'               => '+10:00',
            'Asia/Yakutsk'                   => '+09:00',
            'Asia/Yangon'                    => '+06:30',
            'Asia/Yekaterinburg'             => '+05:00',
            'Asia/Yerevan'                   => '+04:00',
            'Atlantic/Azores'                => '−01:00',
            'Atlantic/Bermuda'               => '−04:00',
            'Atlantic/Canary'                => '+00:00',
            'Atlantic/Cape_Verde'            => '−01:00',
            'Atlantic/Faroe'                 => '+00:00',
            'Atlantic/Madeira'               => '+00:00',
            'Atlantic/Reykjavik'             => '+00:00',
            'Atlantic/South_Georgia'         => '−02:00',
            'Atlantic/St_Helena'             => '+00:00',
            'Atlantic/Stanley'               => '−03:00',
            'Australia/Adelaide'             => '+09:30',
            'Australia/Brisbane'             => '+10:00',
            'Australia/Broken_Hill'          => '+09:30',
            'Australia/Currie'               => '+10:00',
            'Australia/Darwin'               => '+09:30',
            'Australia/Eucla'                => '+08:45',
            'Australia/Hobart'               => '+10:00',
            'Australia/Lindeman'             => '+10:00',
            'Australia/Lord_Howe'            => '+10:30',
            'Australia/Melbourne'            => '+10:00',
            'Australia/Perth'                => '+08:00',
            'Australia/Sydney'               => '+10:00',
            'Europe/Amsterdam'               => '+01:00',
            'Europe/Andorra'                 => '+01:00',
            'Europe/Astrakhan'               => '+04:00',
            'Europe/Athens'                  => '+02:00',
            'Europe/Belgrade'                => '+01:00',
            'Europe/Berlin'                  => '+01:00',
            'Europe/Bratislava'              => '+01:00',
            'Europe/Brussels'                => '+01:00',
            'Europe/Bucharest'               => '+02:00',
            'Europe/Budapest'                => '+01:00',
            'Europe/Busingen'                => '+01:00',
            'Europe/Chisinau'                => '+02:00',
            'Europe/Copenhagen'              => '+01:00',
            'Europe/Dublin'                  => '+01:00',
            'Europe/Gibraltar'               => '+01:00',
            'Europe/Guernsey'                => '+00:00',
            'Europe/Helsinki'                => '+02:00',
            'Europe/Isle_of_Man'             => '+00:00',
            'Europe/Istanbul'                => '+03:00',
            'Europe/Jersey'                  => '+00:00',
            'Europe/Kaliningrad'             => '+02:00',
            'Europe/Kiev'                    => '+02:00',
            'Europe/Kirov'                   => '+03:00',
            'Europe/Lisbon'                  => '+00:00',
            'Europe/Ljubljana'               => '+01:00',
            'Europe/London'                  => '+00:00',
            'Europe/Luxembourg'              => '+01:00',
            'Europe/Madrid'                  => '+01:00',
            'Europe/Malta'                   => '+01:00',
            'Europe/Mariehamn'               => '+02:00',
            'Europe/Minsk'                   => '+03:00',
            'Europe/Monaco'                  => '+01:00',
            'Europe/Moscow'                  => '+03:00',
            'Europe/Oslo'                    => '+01:00',
            'Europe/Paris'                   => '+01:00',
            'Europe/Podgorica'               => '+01:00',
            'Europe/Prague'                  => '+01:00',
            'Europe/Riga'                    => '+02:00',
            'Europe/Rome'                    => '+01:00',
            'Europe/Samara'                  => '+04:00',
            'Europe/San_Marino'              => '+01:00',
            'Europe/Sarajevo'                => '+01:00',
            'Europe/Saratov'                 => '+04:00',
            'Europe/Simferopol'              => '+03:00',
            'Europe/Skopje'                  => '+01:00',
            'Europe/Sofia'                   => '+02:00',
            'Europe/Stockholm'               => '+01:00',
            'Europe/Tallinn'                 => '+02:00',
            'Europe/Tirane'                  => '+01:00',
            'Europe/Ulyanovsk'               => '+04:00',
            'Europe/Uzhgorod'                => '+02:00',
            'Europe/Vaduz'                   => '+01:00',
            'Europe/Vatican'                 => '+01:00',
            'Europe/Vienna'                  => '+01:00',
            'Europe/Vilnius'                 => '+02:00',
            'Europe/Volgograd'               => '+04:00',
            'Europe/Warsaw'                  => '+01:00',
            'Europe/Zagreb'                  => '+01:00',
            'Europe/Zaporozhye'              => '+02:00',
            'Europe/Zurich'                  => '+01:00',
            'Indian/Antananarivo'            => '+03:00',
            'Indian/Chagos'                  => '+06:00',
            'Indian/Christmas'               => '+07:00',
            'Indian/Cocos'                   => '+06:30',
            'Indian/Comoro'                  => '+03:00',
            'Indian/Kerguelen'               => '+05:00',
            'Indian/Mahe'                    => '+04:00',
            'Indian/Maldives'                => '+05:00',
            'Indian/Mauritius'               => '+04:00',
            'Indian/Mayotte'                 => '+03:00',
            'Indian/Reunion'                 => '+04:00',
            'Pacific/Apia'                   => '+13:00',
            'Pacific/Auckland'               => '+12:00',
            'Pacific/Bougainville'           => '+11:00',
            'Pacific/Chatham'                => '+12:45',
            'Pacific/Chuuk'                  => '+10:00',
            'Pacific/Easter'                 => '−06:00',
            'Pacific/Efate'                  => '+11:00',
            'Pacific/Enderbury'              => '+13:00',
            'Pacific/Fakaofo'                => '+13:00',
            'Pacific/Fiji'                   => '+12:00',
            'Pacific/Funafuti'               => '+12:00',
            'Pacific/Galapagos'              => '−06:00',
            'Pacific/Gambier'                => '−09:00',
            'Pacific/Guadalcanal'            => '+11:00',
            'Pacific/Guam'                   => '+10:00',
            'Pacific/Honolulu'               => '−10:00',
            'Pacific/Kiritimati'             => '+14:00',
            'Pacific/Kosrae'                 => '+11:00',
            'Pacific/Kwajalein'              => '+12:00',
            'Pacific/Majuro'                 => '+12:00',
            'Pacific/Marquesas'              => '−09:30',
            'Pacific/Midway'                 => '−11:00',
            'Pacific/Nauru'                  => '+12:00',
            'Pacific/Niue'                   => '−11:00',
            'Pacific/Norfolk'                => '+11:00',
            'Pacific/Noumea'                 => '+11:00',
            'Pacific/Pago_Pago'              => '−11:00',
            'Pacific/Palau'                  => '+09:00',
            'Pacific/Pitcairn'               => '−08:00',
            'Pacific/Pohnpei'                => '+11:00',
            'Pacific/Port_Moresby'           => '+10:00',
            'Pacific/Rarotonga'              => '−10:00',
            'Pacific/Saipan'                 => '+10:00',
            'Pacific/Tahiti'                 => '−10:00',
            'Pacific/Tarawa'                 => '+12:00',
            'Pacific/Tongatapu'              => '+13:00',
            'Pacific/Wake'                   => '+12:00',
            'Pacific/Wallis'                 => '+12:00',
            'UTC'                            => '+00:00',
        ];
    }

    ////////////////////////////////////////////////////////////////
}
